### ISSUE TITLE
Caller number not displayed nicely

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/LivePhone-Android#1]
When I get a call in the app instead of the actual caller's number or contact details I can see only <sip:number@ip>
![obrázok](https://user-images.githubusercontent.com/10156080/70517323-bb236900-1b38-11ea-9f55-60a26267d5d2.png)

The same is displayed in the notification and during call.

**Comment by rkostrab** [comment]
fixed in coming v. 1.5.3
